FROM temporalio/server:latest

# Set environment variables to interpolate into the Docker image's config
# template.
# https://github.com/temporalio/temporal/blob/master/docker/config_template.yaml
ENV DB=postgresql
ENV SQL_TLS_ENABLED=true